package io.github.repopulse.report;

import io.github.repopulse.model.FileMetrics;
import io.github.repopulse.model.Finding;
import io.github.repopulse.model.RepoMetrics;

import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Renders a {@link RepoMetrics} into a human-friendly Markdown health report.
 * This is the artifact committed daily by the GitHub Action.
 */
public final class MarkdownReport {

    public String render(RepoMetrics m) {
        StringBuilder sb = new StringBuilder();
        String generated = ZonedDateTime.now(ZoneOffset.UTC)
                .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'"));

        sb.append("# RepoPulse Health Report\n\n");
        sb.append("_Generated ").append(generated).append(" for `")
                .append(m.rootName()).append("`._\n\n");
        sb.append("> Auto-generated by [RepoPulse](https://github.com). ")
                .append("Re-run with `java -jar repopulse.jar <path>`.\n\n");

        // --- Summary scoreboard ---
        sb.append("## Summary\n\n");
        sb.append("| Metric | Value |\n");
        sb.append("|---|---|\n");
        sb.append("| Onboarding readiness | ").append(scoreBar(m.onboardingScore())).append(" |\n");
        sb.append("| Build tool | ").append(m.buildTool()).append(" |\n");
        sb.append("| Java files | ").append(m.javaFileCount()).append(" |\n");
        sb.append("| Lines of code | ").append(m.codeLines())
                .append(" (").append(m.totalLines()).append(" total) |\n");
        sb.append("| Types declared | ").append(m.typeCount()).append(" |\n");
        sb.append("| Getter/setter methods | ").append(m.getterSetterCount()).append(" |\n");
        sb.append("| Record/Lombok candidates | ").append(m.recordCandidateCount()).append(" |\n");
        sb.append("| TODO / FIXME markers | ").append(m.todoCount()).append(" |\n\n");

        // --- Onboarding checklist ---
        sb.append("## Onboarding checklist\n\n");
        sb.append(check(!m.buildTool().equals("unknown"),
                "Recognised build tool (" + m.buildTool() + ")"));
        sb.append(check(m.hasReadme(), "README present"));
        sb.append(check(m.hasTests(), "Test directory (`src/test`)"));
        sb.append(check(m.hasCi(), "CI workflows (`.github/workflows`)"));
        sb.append(check(m.hasGitignore(), "`.gitignore` present"));
        sb.append(check(m.hasLicense(), "LICENSE present"));
        sb.append("\n");

        // --- Findings ---
        sb.append("## Findings\n\n");
        if (m.findings().isEmpty()) {
            sb.append("No issues detected.\n\n");
        } else {
            sb.append("| Severity | Category | Finding | Location |\n");
            sb.append("|---|---|---|---|\n");
            List<Finding> sorted = m.findings().stream()
                    .sorted(Comparator.comparing(Finding::severity).reversed())
                    .collect(Collectors.toList());
            for (Finding f : sorted) {
                sb.append("| ").append(badge(f.severity()))
                        .append(" | ").append(f.category())
                        .append(" | ").append(f.message())
                        .append(" | `").append(f.location()).append("` |\n");
            }
            sb.append("\n");
        }

        // --- Boilerplate hotspots ---
        List<FileMetrics> hotspots = m.files().stream()
                .filter(f -> f.getterSetterCount() > 0)
                .sorted(Comparator.comparingInt(FileMetrics::getterSetterCount).reversed())
                .limit(10)
                .collect(Collectors.toList());
        if (!hotspots.isEmpty()) {
            sb.append("## Boilerplate hotspots\n\n");
            sb.append("Files with the most getter/setter boilerplate (top candidates for ")
                    .append("records or Lombok):\n\n");
            sb.append("| File | Getters/Setters | Lines | Record candidate |\n");
            sb.append("|---|---|---|---|\n");
            for (FileMetrics f : hotspots) {
                sb.append("| `").append(f.path()).append("` | ")
                        .append(f.getterSetterCount()).append(" | ")
                        .append(f.codeLines()).append(" | ")
                        .append(f.recordCandidate() ? "yes" : "no").append(" |\n");
            }
            sb.append("\n");
        }

        // --- Largest files ---
        List<FileMetrics> largest = m.files().stream()
                .sorted(Comparator.comparingInt(FileMetrics::codeLines).reversed())
                .limit(5)
                .collect(Collectors.toList());
        if (!largest.isEmpty()) {
            sb.append("## Largest source files\n\n");
            for (FileMetrics f : largest) {
                sb.append("- `").append(f.path()).append("` - ")
                        .append(f.codeLines()).append(" lines of code\n");
            }
            sb.append("\n");
        }

        sb.append("---\n");
        sb.append("RepoPulse is a zero-dependency, single-purpose tool. ")
                .append("This report is regenerated automatically; review it like any other diff.\n");
        return sb.toString();
    }

    private String scoreBar(int score) {
        int filled = Math.round(score / 10f);
        StringBuilder bar = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            bar.append(i < filled ? "#" : "-");
        }
        return "`[" + bar + "]` " + score + "/100";
    }

    private String check(boolean ok, String label) {
        return "- [" + (ok ? "x" : " ") + "] " + label + "\n";
    }

    private String badge(Finding.Severity s) {
        switch (s) {
            case WARNING: return "WARNING";
            case SUGGESTION: return "Suggestion";
            default: return "Info";
        }
    }
}
